name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
            submodules: true
            token: ${{ secrets.PAT }}
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: "package-lock.json"
  
      - name: Install
        shell: "bash"
        run: |
          npm install
  
      - name: Build
        shell: "bash" 
        run: |
          npx quartz build
      - name: setup git
        shell: "bash"
        run: | 
          sudo apt-get install -y git

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site